drop table if exists users cascade;
drop table if exists items cascade;
drop table if exists bookings cascade;
drop table if exists comments cascade;

CREATE TABLE IF NOT EXISTS users
(
    id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100)                         NOT NULL,
    email VARCHAR(200)                         NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists items
(
    id          int generated by default as identity not null,
    name        varchar(100)                         not null,
    description varchar(500)                         not null,
    owner_id    int references users (id),
    available   boolean                              not null,
    constraint pk_item primary key (id)
);

create table if not exists bookings
(
    id         int generated by default as identity not null,
    item_id    int references items (id),
    booker_id  int references users (id),
    start_date timestamp without time zone,
    end_date   timestamp without time zone,
    status     varchar(10),
    constraint pk_booking primary key (id)
);

create table if not exists comments
(
    id        int generated by default as identity not null,
    text      varchar(500),
    item_id   int references items (id),
    author_id int references users (id)
);